### ISSUE TITLE
Basic docs

### ISSUE THREAD

**Issue by Robinlovelace** [Urban-Analytics-Technology-Platform/od2net#39]
I know this is work in progress but thought I'd give it a spin. Things I've tried so far based on looking at https://github.com/dabreegster/od2net/blob/main/examples/run_all.sh

I've tried:

```
cd examples/liverpool/
python setup.py 
Traceback (most recent call last):
  File "/home/robin/github/people/dabreegster/od2net/examples/liverpool/setup.py", line 109, in <module>
    run(["mkdir", "-p", "input"])
NameError: name 'run' is not defined
```

**Comment by Robinlovelace** [comment]
Found it:

https://github.com/dabreegster/od2net/blob/77a3aa251991b1499e28510e346654c5cc38337c/examples/utils.py#L4

**Comment by dabreegster** [comment]
The `sys.path.append("..")` is some hack to find `utils.py` from each example directory. I know I need to make the python module stuff work properly. But odd that it's not working for you -- to sanity check, what's `python --version`? If it's using 2.7 for some odd reason, try `python3`

**Comment by Robinlovelace** [comment]
```
python --version                                                                                                                          10/17/2023 01:13:21 pm
Python 3.10.12
```

I think I'm doing something wrong/non-standard. Happy to explore and learn more.

**Comment by dabreegster** [comment]
Hi Robin, would you mind trying this again please? https://github.com/Urban-Analytics-Technology-Platform/od2net/blob/main/docs/tutorial_examples.md
Either start fresh or make sure to `git pull`. I think I finally solved the weird Python import problem you kept hitting

**Comment by Robinlovelace** [comment]
will give it a bash, tomorrow most likely

**Comment by Robinlovelace** [comment]
OK, going to give it a quick go now.

**Comment by Robinlovelace** [comment]
Seems to be working
